preprocessing:
  resample_audio_folder: ./data
  times: 4 # seconds, ESC:5, Urbsound8k:4
  new_sr: 16000  # 16k 比8k 好
  # feature: stft
  feature: mel
  mel_arg:
    power: 2
    n_fft: 2048  # 2048比1024好
    hop_length: 1024  # 和320差不多, 育大愈好
    n_mels: 128
    # fmin: 100
    fmax: 8000
    norm: slaney
  stft_arg:
    n_fft: 512 
    hop_length: 256
  dbscale: True  # 一定要有
  normalize: False # 不論有沒有dbscale, 這個不一定要有

dataset: Urbsound8k  # ESC  Urbsound8k
# dataset: ESC  # ESC  Urbsound8k
ESC_dataset:
  audio_folder: /home/siuoly/ml/datasets/ESC-50-master/audio/
  meta_file: /home/siuoly/ml/datasets/ESC-50-master/meta/esc50.csv
Urbsound8k_dataset:
  audio_folder: /home/siuoly/ml/datasets/UrbanSound8K/audio/
  meta_file: /home/siuoly/ml/datasets/UrbanSound8K/metadata/UrbanSound8K.csv

feature_folder: ./data/db_noNorm_sr16000_nfft2048_hop320_n_mels128/ #  0.707
feature_folder: ./data/xx
model:
  name: GeneralCnn
  arg:
    cnn:  # inch,outch,ker,stride,padding,poolker
      - [16,3,1,2,2]
      - [16,32,3,1,2,2]
      - [32,64,3,1,2,2]
      - [128,128,3,1,2,2]
    linear: 256
exp_folder: ./exp/test1/
num_epoch: 150
batch_size: 64
lr: 4e-4  # 隨著適合的 batch_size 而變化
num_class: 50
testfold: 1
in_channel: 1
transform: True
message: ""
